### ISSUE TITLE
Close issues before final acceptance

### ISSUE THREAD

**Issue by irismolinari** [inforlife/process#11]
Shall we close issues before final acceptance so that in the milestone page we can easily see what is still pending?
If an issue is not accepted, we can always reopen it.

This should be updated in [Overview](https://github.com/inforlife/process/blob/master/overview.md) and in [Acceptance](https://inforlife.github.io/process/iterations.html#user-acceptance).

**Comment by sigfrid** [comment]
@irismolinari can you please confirm we decided to do so (close before acceptance)?
We also agreed on keeping, in `Project`, the closed issue in the `Completed` column until acceptance. Then, we will move them to `Done` until the Milestone is deployed to production. At the point, all the Issues are removed from `Project`. Correct?

**Comment by irismolinari** [comment]
Yes this what we decided.
The only thing we could update is the final step. Instead of removing the cards from `Project`, we could [archive](https://blog.github.com/2018-06-28-archive-project-board-cards/) them.

**Comment by sigfrid** [comment]
👍
