### ISSUE TITLE
Manage nullified issues

### ISSUE THREAD

**Issue by irismolinari** [inforlife/process#12]
What should be done if a issue must be nullified?

**Comment by sigfrid** [comment]
@irismolinari at which stage of the process are you thinking about?
For which reasons an Issue may need to be nullified?

**Comment by irismolinari** [comment]
Before development of a issue we could decide it is no more necessary. 
See examples [here](https://github.com/inforlife/traininghub/issues?q=is%3Aissue+is%3Aclosed+label%3Anullified)
